---
- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: test connections
      ping:
    - name: update system to latest
      apt: update_cache=yes upgrade=dist
    - name: install default packages
      apt: pkg={{ item }} state=installed
      with_items:
        - build-essential
        - bison
        - openssl
        - libreadline6
        - libreadline6-dev
        - curl
        - git-core
        - zlib1g
        - zlib1g-dev
        - libssl-dev
        - libyaml-dev
        - libsqlite3-0
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - autoconf
        - libc6-dev
        - libncurses5-dev
        - nginx
        - postgresql
        - postgresql-server-dev-9.1
        - libpq-dev
        - python-psycopg2

- hosts: vagrant
  remote_user: vagrant

  tasks:
  - name: install ruby-dev
    apt: pkg=ruby-dev state=installed
    sudo: yes
  - name: install bundler
    # I could not get get gem module to install it
    # so i am just going to use a more standard shell way
    # gem: name=bundler state=latest
    action: shell gem install bundler --no-ri --no-rdoc
    sudo: yes
  - name: install gems with binstubs
    command: chdir=/vagrant/ bundle install --binstubs

- hosts: vagrant
  remote_user: vagrant
  tasks:
    - name: copy database config template
      file: src=/vagrant/config/database.yml.development dest=/vagrant/config/database.yml state=link

- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: remove nginx default
      file: dest=/etc/nginx/sites-enabled/default state=absent
    - name: set nginx conf for development
      file: src=/vagrant/config/nginx.conf.development dest=/etc/nginx/sites-enabled/beamtous state=link
      notify:
      - restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

- hosts: vagrant
  remote_user: vagrant
  tasks:
    - name: create folder for pids
      file: dest=/vagrant/tmp/pids state=directory

- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: symlink unicorn_development_init
      file: src=/vagrant/config/unicorn_development_init.sh dest=/etc/init.d/unicorn state=link
      notify:
      - restart unicorn
  handlers:
    - name: restart unicorn
      service: name=unicorn state=started

- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  sudo_user: postgres

  vars:
    dbname: beamtous_development
    dbuser: vagrant
    dbpassword: password1

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  tasks:
  - name: install elasticsearch prerequisties
    apt: pkg=openjdk-7-jre-headless state=installed
  - name: download deb file
    get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.8.deb dest=/tmp
  - name: install elasticsearch
    shell: "dpkg -i /tmp/elasticsearch-0.90.8.deb"
  - name: remove the debian package
    file: dest=/tmp/elasticsearch-0.90.8.deb state=absent

- hosts: vagrant
  remote_user: vagrant
  tasks:
    - name: restore from backup
      shell: "cat /vagrant/beamtous-latest.sql.gz | gunzip | psql beamtous_development"
